services:
#    xm_admin.example:
#        class: Xm\AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    xm:
        class:     Xm\AdminBundle\Util\Xm
        arguments: ["@service_container"]